### ISSUE TITLE
Broken dependency django-paypal == 0.1.2.lfs-2

### ISSUE THREAD

**Issue by pigletto** [diefenbach/django-lfs#193]
It is not possible to install LFS with such version of django-paypal: "Could not find a version that satisfies the requirement django-paypal==0.1.2.lfs-2"

**Comment by endthestart** [comment]
I'm also getting this issue. I was unable to install anything manually that would resolve the issue.

**Comment by diefenbach** [comment]
The buildout must point to http://pypi.iqpp.de/ (which it does by with the default installer). 

find-links =
    http://pypi.iqpp.de/

The package is there, see:

http://pypi.iqpp.de/

**Comment by tyrielbr** [comment]
I dont get it working... 

even I setting up it I cant make my environment working, i setup it alone pip install lfs-paylpal and also django-paypal and everything else and still cant get this thing running... i am just about to change to another ecommerce because the installation simply gets me freakout
